# Generated by Django 3.1.5 on 2021-04-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20210323_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
